# ratios: loc_comments=108:10 imports_exports=5:7 calls_definitions=54:7
#!/usr/bin/env python3
"""Build thin Codex plugin adapters for every canonical skill-lib skill.

Usage guidance:
    python tools/build_codex_plugin_skills.py --check
    python tools/build_codex_plugin_skills.py --apply

Canonical skill doctrine remains in ``<skill-name>/SKILL.md``. Generated files
under ``skills/`` contain only discovery metadata and an instruction to load
that canonical source. Do not edit generated adapters by hand.
"""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INDEX = ROOT / "skills.json"
OUTPUT = ROOT / "skills"
HEADER = "<!-- Generated by tools/build_codex_plugin_skills.py; do not edit. -->"


def canonical_frontmatter(path: Path) -> dict[str, str]:
    """Parse the dependency-free YAML subset used by canonical SKILL.md files."""
    text = path.read_text(encoding="utf-8")
    try:
        _, raw, _ = text.split("---\n", 2)
    except ValueError as exc:
        raise ValueError(f"missing canonical frontmatter: {path}") from exc

    lines = raw.splitlines()
    data: dict[str, str] = {}
    index = 0
    while index < len(lines):
        line = lines[index]
        index += 1
        if ":" not in line or line.startswith((" ", "\t")):
            continue
        key, raw_value = line.split(":", 1)
        key = key.strip()
        value = raw_value.strip()
        if value in {">", ">-", "|", "|-"}:
            parts: list[str] = []
            while index < len(lines):
                continuation = lines[index]
                if continuation and not continuation.startswith((" ", "\t")):
                    break
                parts.append(continuation.strip())
                index += 1
            data[key] = (
                "\n".join(parts).strip()
                if value.startswith("|")
                else " ".join(part for part in parts if part).strip()
            )
            continue
        data[key] = value.strip('"\'')
    return data


def canonical_metadata(skill: dict[str, object]) -> tuple[str, str, str]:
    canonical_path = str(skill["path"])
    metadata = canonical_frontmatter(ROOT / canonical_path)
    name = metadata.get("name", "")
    description = metadata.get("description", "")
    if name != str(skill["name"]):
        raise ValueError(
            f"canonical name mismatch for {canonical_path}: {name!r} != {skill['name']!r}"
        )
    if not description:
        raise ValueError(f"canonical description missing for {canonical_path}")
    return name, description, canonical_path


def adapter(skill: dict[str, object]) -> str:
    name, canonical_description, canonical_path = canonical_metadata(skill)
    description = json.dumps(canonical_description, ensure_ascii=False)
    return (
        f"---\nname: {name}\ndescription: {description}\n---\n\n"
        f"{HEADER}\n\n"
        f"Read and follow `../../{canonical_path}` completely before acting. "
        "That file is the canonical skill; this adapter only exposes it through "
        "the Codex plugin skill directory.\n"
    )


def expected() -> dict[Path, str]:
    data = json.loads(INDEX.read_text(encoding="utf-8"))
    return {
        OUTPUT / str(skill["name"]) / "SKILL.md": adapter(skill)
        for skill in data["skills"]
    }


def drift() -> list[str]:
    wanted = expected()
    findings: list[str] = []
    actual = set(OUTPUT.glob("*/SKILL.md")) if OUTPUT.exists() else set()
    for path, content in wanted.items():
        if not path.exists():
            findings.append(f"missing: {path.relative_to(ROOT)}")
        elif path.read_text(encoding="utf-8") != content:
            findings.append(f"drift: {path.relative_to(ROOT)}")
    for path in sorted(actual - set(wanted)):
        findings.append(f"unexpected: {path.relative_to(ROOT)}")
    return findings


def apply() -> None:
    wanted = expected()
    OUTPUT.mkdir(exist_ok=True)
    actual_dirs = {path.parent for path in OUTPUT.glob("*/SKILL.md")}
    wanted_dirs = {path.parent for path in wanted}
    for directory in sorted(actual_dirs - wanted_dirs):
        shutil.rmtree(directory)
    for path, content in wanted.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--apply", action="store_true")
    args = parser.parse_args()

    if args.apply:
        apply()
    findings = drift()
    if findings:
        print("\n".join(findings))
        return 1
    print(f"Codex plugin adapters: pass ({len(expected())} skills)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
# ratios: loc_comments=108:10 imports_exports=5:7 calls_definitions=54:7
