from __future__ import annotations

import json
import unittest
from pathlib import Path

from frontmatter import frontmatter_for


ROOT = Path(__file__).resolve().parents[1]
SKILL = ROOT / "action-calibration" / "SKILL.md"
CRITERIA = ROOT / "action-calibration" / "references" / "thread-derived-criteria.md"
AUDIT = ROOT / "action-calibration" / "references" / "savings-skill-audit.md"
CASES = ROOT / "action-calibration" / "examples" / "cases.json"
ADAPTER = ROOT / "skills" / "action-calibration" / "SKILL.md"


class ActionCalibrationSkillTest(unittest.TestCase):
    def setUp(self) -> None:
        self.text = SKILL.read_text(encoding="utf-8")
        self.frontmatter = frontmatter_for(SKILL)
        self.criteria = CRITERIA.read_text(encoding="utf-8")
        self.audit = AUDIT.read_text(encoding="utf-8")
        self.cases = json.loads(CASES.read_text(encoding="utf-8"))

    def test_activation_and_non_trigger_are_concrete(self) -> None:
        description = self.frontmatter["description"]
        for phrase in (
            "smallest decisive experiment",
            "maximal coherent program",
            "highest-leverage action",
            "time, attention, money, compute, or coordination constraints",
            "Do not load",
            "trivial fixed-scope task",
            "immediate emergency containment",
        ):
            with self.subTest(phrase=phrase):
                self.assertIn(phrase, description)

    def test_minimal_and_maximal_are_not_flattened(self) -> None:
        self.assertIn(
            "minimal decisive action != smallest visible deliverable", self.text
        )
        self.assertIn(
            "maximal coherent action  != everything that could possibly be done",
            self.text,
        )
        self.assertIn("Branch-change test", self.text)
        self.assertIn("Coupling test", self.text)

    def test_three_outcome_branches_and_stop_conditions_are_required(self) -> None:
        for required in (
            "positive_outcome:",
            "negative_outcome:",
            "unresolved_outcome:",
            "stop_condition:",
            "escalation_rule:",
            "Freeze criteria before evaluation",
        ):
            with self.subTest(required=required):
                self.assertIn(required, self.text)

    def test_complete_cost_vector_is_preserved(self) -> None:
        for cost in (
            "time:",
            "human_attention:",
            "money:",
            "compute:",
            "coordination:",
            "operational_risk:",
        ):
            self.assertIn(cost, self.text)

    def test_existing_skill_boundaries_are_explicit(self) -> None:
        for skill in (
            "`loop-eng`",
            "`interdependent-work-graph`",
            "`meta-module-build`",
            "`risk-boundary-build`",
            "`canon`",
            "`domain-claims`",
            "`char-compress`",
            "`distributed-publication`",
            "`skill-usage`",
        ):
            with self.subTest(skill=skill):
                self.assertIn(skill, self.text)

    def test_thread_criteria_preserve_negative_and_control_results(self) -> None:
        for phrase in (
            "Use an obstruction before a global search",
            "Add a same-protocol control",
            "Escalate evidence only when load-bearing",
            "Freeze criteria before inspecting outcomes",
            "one four-component sublink",
        ):
            with self.subTest(phrase=phrase):
                self.assertIn(phrase, self.criteria)

    def test_audit_creates_one_skill_and_routes_adjacent_patterns(self) -> None:
        self.assertIn("That gap justifies `action-calibration`", self.audit)
        self.assertIn("Strong future skill candidate 1: `evidence-ladder`", self.audit)
        self.assertIn(
            "Strong future skill candidate 2: `preregistered-evaluation`", self.audit
        )
        self.assertIn("Rejected candidate skills", self.audit)
        self.assertIn("A skill that saves execution", self.audit)

    def test_cases_cover_minimal_maximal_prerequisite_and_nontrigger(self) -> None:
        choices = {case["expected_choice"] for case in self.cases["cases"]}
        self.assertTrue(
            {"minimal", "maximal", "prerequisite_repair", "immediate_containment"}
            <= choices
        )
        self.assertTrue(any(not case["activate"] for case in self.cases["cases"]))
        self.assertTrue(any(case["activate"] for case in self.cases["cases"]))

    def test_codex_adapter_points_to_canonical_skill(self) -> None:
        text = ADAPTER.read_text(encoding="utf-8")
        self.assertIn("Generated by tools/build_codex_plugin_skills.py", text)
        self.assertIn("../../action-calibration/SKILL.md", text)


if __name__ == "__main__":
    unittest.main()
