from __future__ import annotations

import unittest
from pathlib import Path

from frontmatter import frontmatter_for


ROOT = Path(__file__).resolve().parents[1]
SKILL = ROOT / "ucns-option-selection" / "SKILL.md"
ADAPTER = ROOT / "skills" / "ucns-option-selection" / "SKILL.md"
GONOL_BUILD = ROOT / "gonol-build" / "SKILL.md"


class UcnsOptionSelectionSkillTest(unittest.TestCase):
    def setUp(self) -> None:
        self.text = SKILL.read_text(encoding="utf-8")
        self.frontmatter = frontmatter_for(SKILL)

    def test_activation_and_nontrigger_are_explicit(self) -> None:
        description = self.frontmatter["description"]
        for phrase in (
            "which UCNS candidate should win",
            "competing gonol constructors",
            "Do not load",
            "ordinary UI preferences",
        ):
            self.assertIn(phrase, description)

    def test_hard_gates_cannot_be_compensated(self) -> None:
        self.assertIn("Selection is a gated decision, not an additive score", self.text)
        self.assertIn("cannot compensate for a violated invariant", self.text)
        self.assertIn("hard gates remain independently visible", self.text)

    def test_scope_identity_evidence_and_replay_are_required(self) -> None:
        for phrase in (
            "Fix the decision boundary",
            "Resolve exact candidate identity",
            "Apply hard eligibility gates",
            "Require complete evidence",
            "Require falsification and independent replay",
            "Seal the decision receipt",
        ):
            self.assertIn(phrase, self.text)

    def test_all_terminal_standings_are_defined(self) -> None:
        for standing in (
            "SELECTED_FOR_SCOPE",
            "RETAINED_CANDIDATE",
            "REJECTED",
            "BLOCKED",
            "UNRESOLVED",
            "DEPRECATED",
        ):
            self.assertIn(standing, self.text)

    def test_ratification_and_nontransfer_are_explicit(self) -> None:
        self.assertIn("named authority performs the required ratification", self.text)
        self.assertIn("cannot substitute for ratification", self.text)
        self.assertIn("non-transfer boundaries", self.text)

    def test_unresolved_authorizes_candidate_work_not_promotion(self) -> None:
        self.assertIn("does not block candidate", self.text)
        self.assertIn("candidate from being built or tested", self.text)
        gonol_text = GONOL_BUILD.read_text(encoding="utf-8")
        gonol_compact = " ".join(gonol_text.split())
        self.assertIn("permission to construct a named, bounded", gonol_compact)
        self.assertIn("does not block declared experimentation", gonol_compact)

    def test_codex_adapter_points_to_canonical_skill(self) -> None:
        text = ADAPTER.read_text(encoding="utf-8")
        self.assertIn("Generated by tools/build_codex_plugin_skills.py", text)
        self.assertIn("../../ucns-option-selection/SKILL.md", text)


if __name__ == "__main__":
    unittest.main()
